services:
  stats-server:
      build: ./stats-service/stats-server
      image: stats-server
      container_name: stats-server
      ports:
        - "9090:9090"
      depends_on:
        - stats-db
      environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
        - SPRING_DATASOURCE_USERNAME=stats
        - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./ewm-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
        - ewm-db
        - stats-server
    environment:
        - STATS_SERVER_URL=http://stats-server:9090
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
        - SPRING_DATASOURCE_USERNAME=ewm
        - SPRING_DATASOURCE_PASSWORD=ewm

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10